## Testando criação de usuário

POST https://secomp-server-xiv-production.up.railway.app/api/v1/users/signup
Content-Type: application/json

{
    "email": "teste@teste.com.br",
    "nome": "teste jr",
    "senha": "senha1"
}

### Testando login de usuário já cadastrado
POST http://localhost:3333/api/v1/users/login
Content-Type: application/json

{
    "email": "teste@teste.com",
    "senha": "senha1"
}

### Testando login de usuário não cadastrado
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "erro@teste.com",
    "senha": "senha_erro"
}

### Testando login de usuário com senha errada
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "teste@teste.com",
    "senha": "senha_errada"
}

### Testando login com sucesso
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "teste@teste.com",
    "senha": "senha1"
}

### Testando registro de token de push
POST http://localhost:3333/api/v1/users/registerPushToken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1YTFkYTQxNS02N2IyLTQzNzAtOTBlNS1jZjg5MTU0N2IwMmEiLCJpYXQiOjE3NTE0OTY0OTUsImV4cCI6MTc1MTUwMDA5NX0.i3b1LCjQ8yP5nbJl529Tdg7PFaqO45HzldmK_OFPZnc
Content-Type: application/json

{
    "token": "ExponentPushToken[exemplo123]"
}


### Enviar notificação push para um usuário
POST http://localhost:3333/api/v1/notifications/send
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhN2ZhMTIwOS1lYjUzLTQwNTMtODc5Ni0zZTdiZjQ2ODkzZmUiLCJpYXQiOjE3NTcwMzEwMTUsImV4cCI6MTc1NzAzNDYxNX0.nbt_Xh_PPogTS0pZUDVrcxl2ZI2Pr3k3LCmok-VkUKU
Content-Type: application/json

{
  "recipientIds": ["a7fa1209-eb53-4053-8796-3e7bf46893fe"],
  "title": "SECOMP UFSCar",
  "message": "Você acabou de receber uma notificação!",
  "data": {
    "tipo": "teste"
  },
  "sound": true,
  "badge": 1
}

### Enviar notificação push para todos os usuários
POST http://localhost:3333/api/v1/notifications/send-to-all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhN2ZhMTIwOS1lYjUzLTQwNTMtODc5Ni0zZTdiZjQ2ODkzZmUiLCJpYXQiOjE3NTM5MDg4MDcsImV4cCI6MTc1MzkxMjQwN30.cNLogeg6zuffZksSczMinSx_CP2zE0c-TmCPkr-shbU
Content-Type: application/json

{
  "title": "SECOMP UFSCar",
  "message": "Esta é uma notificação enviada para todos os usuários!",
  "data": {
    "tipo": "geral"
  },
  "sound": true,
  "badge": 1
}

### Obter histórico de notificações por usuário
GET http://localhost:3333/api/v1/notifications/history
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhN2ZhMTIwOS1lYjUzLTQwNTMtODc5Ni0zZTdiZjQ2ODkzZmUiLCJpYXQiOjE3NTM5MjMwMzYsImV4cCI6MTc1MzkyNjYzNn0.MQ_tTFWWjdV88rv9zaonDlxGJSFoCVBGn7dCrmofGso
Content-Type: application/json

{
  "userId": "a7fa1209-eb53-4053-8796-3e7bf46893fe"
}