ALTER TABLE `atividades`
  ADD COLUMN `palestranteTitulo` ENUM('APRESENTADOR', 'APRESENTADORA') NOT NULL DEFAULT 'APRESENTADOR',
  ADD COLUMN `localLink` VARCHAR(2048) NULL,
  MODIFY COLUMN `detalhes` VARCHAR(1000) NULL;
